name: LeaderboardsPlus
version: ${project.version}
main: dev.negativekb.leaderboardsplus.LeaderboardsPlus
depend: [PlaceholderAPI]

commands:
  forcerefresh:
    description: Forcefully refresh the leaderboards
    usage: /<command>